"""Empirical convergence-order estimation for numerical engines.

A discretisation scheme is said to converge with order ``p`` if the error
behaves like ``err(h) = C * h**p * (1 + o(1))`` as the step size ``h`` goes to
zero.  Taking logarithms turns this into a straight line,

    log(err) = log(C) + p * log(h),

so the observed order is the slope of an ordinary least-squares fit of
``log(err)`` on ``log(h)``.  This module does exactly that and nothing more:
it is a measurement tool, not a solver.

Conventions used here
---------------------
- ``h`` is a *step size*, i.e. it decreases as the discretisation is refined.
  For a refinement sequence indexed by a node count ``n``, pass ``h = 1/n``.
- ``residual`` is the root-mean-square of the residuals *in log space*
  (units: log-error).  It is zero to round-off for data generated by an exact
  power law and grows as the data departs from one.  R-squared is deliberately
  not used: it saturates near 1.0 for any decent power law and therefore
  discriminates poorly between a clean order and a contaminated one.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass

import numpy as np

from ..exceptions import InvalidInputError

__all__ = ["ConvergenceFit", "fit_convergence_order", "refinement_errors"]


@dataclass(frozen=True, eq=False)
class ConvergenceFit:
    """Result of a least-squares convergence-order fit.

    Parameters
    ----------
    order
        Fitted slope ``p`` of ``log(err)`` against ``log(h)``.
    log_constant
        Fitted intercept ``log(C)`` (natural log).
    residual
        Root-mean-square of the log-space residuals.  ``0.0`` for an exact
        power law; strictly positive for noisy or pre-asymptotic data.
    n_points
        Number of refinement levels used in the fit.
    h
        Step sizes used (read-only copy of the input).
    err
        Errors used (read-only copy of the input).
    """

    order: float
    log_constant: float
    residual: float
    n_points: int
    h: np.ndarray
    err: np.ndarray

    def predict(self, h: float) -> float:
        """Error predicted by the fitted power law at step size ``h``."""
        if not np.isfinite(h) or h <= 0.0:
            raise InvalidInputError("h must be finite and > 0")
        return float(np.exp(self.log_constant + self.order * np.log(h)))


def _as_clean_1d(values: Sequence[float] | np.ndarray, name: str) -> np.ndarray:
    arr = np.asarray(values, dtype=float)
    if arr.ndim != 1:
        raise InvalidInputError(f"{name} must be one-dimensional")
    if not np.all(np.isfinite(arr)):
        raise InvalidInputError(f"{name} must be finite")
    if not np.all(arr > 0.0):
        raise InvalidInputError(f"{name} must be strictly positive")
    return arr


def fit_convergence_order(
    h: Sequence[float] | np.ndarray,
    err: Sequence[float] | np.ndarray,
) -> ConvergenceFit:
    """Fit the empirical convergence order of a refinement sequence.

    Performs an ordinary least-squares fit of ``log(err)`` on ``log(h)`` and
    reports the slope as the observed order.

    Parameters
    ----------
    h
        Step sizes, strictly positive, finite, and strictly monotone (either
        increasing or decreasing).  Use ``1/n`` when the refinement is indexed
        by a node or step count ``n``.
    err
        Errors at the corresponding step sizes, strictly positive and finite.

    Returns
    -------
    ConvergenceFit

    Raises
    ------
    InvalidInputError
        If fewer than three points are supplied, if the arrays differ in
        length, if any value is non-finite or non-positive, or if ``h`` is not
        strictly monotone (a repeated ``h`` makes the slope ill-posed).
    """
    h_arr = _as_clean_1d(h, "h")
    err_arr = _as_clean_1d(err, "err")

    if h_arr.size != err_arr.size:
        raise InvalidInputError("h and err must have the same length")
    if h_arr.size < 3:
        raise InvalidInputError("at least 3 refinement levels are required")

    diffs = np.diff(h_arr)
    if not (np.all(diffs > 0.0) or np.all(diffs < 0.0)):
        raise InvalidInputError("h must be strictly monotone")

    log_h = np.log(h_arr)
    log_err = np.log(err_arr)

    design = np.vstack([log_h, np.ones_like(log_h)]).T
    (slope, intercept), *_ = np.linalg.lstsq(design, log_err, rcond=None)

    fitted = intercept + slope * log_h
    residual = float(np.sqrt(np.mean((log_err - fitted) ** 2)))

    h_out = h_arr.copy()
    err_out = err_arr.copy()
    h_out.setflags(write=False)
    err_out.setflags(write=False)

    return ConvergenceFit(
        order=float(slope),
        log_constant=float(intercept),
        residual=residual,
        n_points=int(h_arr.size),
        h=h_out,
        err=err_out,
    )


def refinement_errors(
    fn: Callable[[int], float],
    levels: Iterable[int],
) -> tuple[np.ndarray, np.ndarray]:
    """Evaluate ``fn`` over refinement ``levels`` and return ``(h, err)``.

    ``fn(level)`` must return the absolute error at that refinement level; the
    matching step size is taken to be ``1 / level``.  This is a convenience
    wrapper for the common ``h = 1/n`` case, nothing more.
    """
    level_list = [int(level) for level in levels]
    if any(level <= 0 for level in level_list):
        raise InvalidInputError("levels must be positive integers")
    h = np.array([1.0 / level for level in level_list], dtype=float)
    err = np.array([float(fn(level)) for level in level_list], dtype=float)
    return h, err
